import fs = require("node:fs");
import path = require("node:path");
import { applySearchReplace, assertSafeBundlePath, summarizeBundleChanges } from "./app-bundle";

export function createAppRoutes(deps: any) {
  const { appsDir, baseUrl, checkAuth, sendJson, clientIp, listApps, withAppLock, backupBundleFiles, atomicWriteFiles, readSession, readVersionHistory, recordVersion, extractTitle, validateGeneratedHtml, genManifest, genIcon } = deps;
  const exists = (dir: string) => dir.startsWith(appsDir) && fs.existsSync(path.join(dir, "index.html"));
  return function handle(req: any, res: any, pathname: string) {
    if (req.method === "GET" && pathname === "/api/apps") { const error = checkAuth(req); return error ? (sendJson(res, 401, { error }), true) : (sendJson(res, 200, { apps: listApps() }), true); }
    const patch = pathname.match(/^\/api\/apps\/([a-z0-9]+)\/patch$/i);
    if (req.method === "POST" && patch) {
      const error = checkAuth(req); if (error) { sendJson(res, 401, { error }); return true; }
      const id = patch[1], dir = path.join(appsDir, id); if (!exists(dir)) { sendJson(res, 404, { error: "应用不存在" }); return true; }
      let bodyText = ""; req.on("data", (chunk: any) => { bodyText += chunk; if (bodyText.length > 2e6) req.destroy(); }); req.on("end", async () => { try {
        const body = JSON.parse(bodyText); if (!Array.isArray(body.patches) || !body.patches.length) return sendJson(res, 400, { error: "patches 不能为空" });
        await withAppLock(id, "patch", async () => {
          const files: Record<string, string> = {}; for (const item of body.patches) { const safe = assertSafeBundlePath(item.path), file = path.join(dir, safe); if (!file.startsWith(dir) || !fs.existsSync(file)) throw new Error("文件不存在：" + safe); files[safe] = fs.readFileSync(file, "utf8"); }
          const before = { entry: "index.html", files }, patched = applySearchReplace(before, body.patches); if (!patched.files["index.html"]) throw new Error("Patch 必须包含 index.html"); const invalid = validateGeneratedHtml(patched.files["index.html"]); if (invalid) throw new Error(invalid);
          const changes = summarizeBundleChanges(before, patched); if (!changes.length) throw new Error("Patch 没有产生实际变化"); const session = readSession(dir), version = session.version || 1, history = Array.isArray(session.history) ? session.history : [], conversation = Array.isArray(session.conversation) ? session.conversation : [];
          backupBundleFiles(dir, changes.map((item: any) => item.path), version); atomicWriteFiles(dir, patched.files); const newVersion = version + 1, title = extractTitle(patched.files["index.html"]), label = "应用增量 Patch：" + changes.map((item: any) => item.path).join(", ");
          const patchConversation = [...conversation, { role: "user", content: label, kind: "message", createdAt: new Date().toISOString() }, { role: "assistant", content: "✅ 已完成：Patch 校验、Diff、版本快照并发布", kind: "step", icon: "✅", createdAt: new Date().toISOString() }].slice(-160);
          const commit = recordVersion(dir, { version: newVersion, action: "patch", message: label, changes, validation: "passed" });
          fs.writeFileSync(path.join(dir, "session.json"), JSON.stringify({ version: newVersion, title, updatedAt: new Date().toISOString(), history: [...history, label].slice(-20), conversation: patchConversation, head: commit.commitId, workflow: { editMode: "patch", validation: "passed", changes, state: "idle" } }));
          sendJson(res, 200, { ok: true, id, version: newVersion, title, commit, changes, url: baseUrl + "/apps/" + id + "/" });
        });
      } catch (e) { sendJson(res, 400, { error: e instanceof Error ? e.message : String(e) }); } }); return true;
    }
    const app = pathname.match(/^\/api\/apps\/([a-z0-9]+)$/i);
    if (req.method === "GET" && app) { const error = checkAuth(req); if (error) { sendJson(res, 401, { error }); return true; } const id = app[1], dir = path.join(appsDir, id); if (!exists(dir)) { sendJson(res, 404, { error: "应用不存在" }); return true; } const session = readSession(dir); let title = session.title || "未命名应用"; if (title === "未命名应用") try { title = extractTitle(fs.readFileSync(path.join(dir, "index.html"), "utf8")); } catch {} const versions = readVersionHistory(dir); sendJson(res, 200, { app: { id, title, version: session.version || 1, versions: versions.length, updatedAt: session.updatedAt || null, history: session.history || [], conversation: session.conversation || [], workflow: session.workflow || null, head: versions[versions.length - 1]?.commitId || null, versionHistory: versions, url: baseUrl + "/apps/" + id + "/" } }); return true; }
    if (req.method === "DELETE" && app) { const error = checkAuth(req); if (error) { sendJson(res, 401, { error }); return true; } const id = app[1], dir = path.join(appsDir, id); if (!dir.startsWith(appsDir) || !fs.existsSync(dir)) { sendJson(res, 404, { error: "应用不存在" }); return true; } fs.rmSync(dir, { recursive: true, force: true }); console.log("[" + new Date().toISOString() + "] 删除 " + id + " · ip=" + clientIp(req)); sendJson(res, 200, { ok: true }); return true; }
    const rollback = pathname.match(/^\/api\/apps\/([a-z0-9]+)\/rollback$/i);
    if (req.method === "POST" && rollback) { const error = checkAuth(req); if (error) { sendJson(res, 401, { error }); return true; } const id = rollback[1], dir = path.join(appsDir, id); if (!dir.startsWith(appsDir) || !fs.existsSync(dir)) { sendJson(res, 404, { error: "应用不存在" }); return true; } (async () => { try { await withAppLock(id, "rollback", async () => { const session = readSession(dir), version = session.version || 1; if (version <= 1) return sendJson(res, 400, { error: "没有可回退的版本" }); const previous = path.join(dir, "versions", "v" + (version - 1) + ".html"); if (!previous.startsWith(dir) || !fs.existsSync(previous)) return sendJson(res, 400, { error: "找不到上一版" }); fs.copyFileSync(path.join(dir, "index.html"), path.join(dir, "versions", "v" + version + ".html")); fs.copyFileSync(previous, path.join(dir, "index.html")); const next = version - 1, title = extractTitle(fs.readFileSync(path.join(dir, "index.html"), "utf8")); fs.writeFileSync(path.join(dir, "manifest.json"), JSON.stringify(genManifest(title, "#4f8cff"), null, 2)); fs.writeFileSync(path.join(dir, "icon.svg"), genIcon(title)); const commit = recordVersion(dir, { version: next, action: "rollback", message: "回退到版本 v" + next, changes: [{ path: "index.html", changed: true, addedChars: 0, removedChars: 0 }], validation: "not-run" }); fs.writeFileSync(path.join(dir, "session.json"), JSON.stringify({ ...session, version: next, title, updatedAt: new Date().toISOString(), head: commit.commitId, workflow: { ...(session.workflow || {}), state: "idle", validation: { status: "not-run" } } })); console.log("[" + new Date().toISOString() + "] 回退 " + id + " · " + title + " · v" + next + " · ip=" + clientIp(req)); sendJson(res, 200, { ok: true, id, version: next, title, commit, url: baseUrl + "/apps/" + id + "/" }); }); } catch (e) { sendJson(res, e instanceof Error && (e as any).statusCode ? Number((e as any).statusCode) : 400, { error: e instanceof Error ? e.message : String(e) }); } })(); return true; }
    return false;
  };
}
